[tool.poetry]
name = "safe_rl"
version = "0.1.0"
description = "A collection of Safe RL experiments that uses ideas from Formal Methods, like Temporal logics, Barrier certificates, Bisimulation functions, etc."
authors = ["Anand Balakrishnan <anandbal@usc.edu>"]


[tool.poetry.dependencies]
python = ">=3.6"
gym = "^0.10.9"
torch = "^1.0"
scipy = "^1.2"
temporal_logic = {git = "https://github.com/anand-bala/tl-py"}
pandas = "*"

[tool.poetry.dev-dependencies]
autopep8 = "^1.4"
pytest = "^4.1"
pylint = "^2.2"
pytest-runner = "^4.2"
pytest-xdist = "^1.26"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
